import { useNavigate } from 'react-router-dom';
import { FileEdit, ArrowLeft } from 'lucide-react';

export default function TermsOfService() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <header className="border-b border-border bg-card/50 backdrop-blur-sm sticky top-0 z-10">
        <div className="container mx-auto px-4 py-4 flex items-center gap-3">
          <button onClick={() => navigate(-1)} className="mr-2 p-2 hover:bg-secondary rounded-lg transition-colors">
            <ArrowLeft className="w-5 h-5 text-muted-foreground" />
          </button>
          <div className="w-10 h-10 rounded-xl bg-primary flex items-center justify-center shadow-elegant">
            <FileEdit className="w-5 h-5 text-primary-foreground" />
          </div>
          <div>
            <h1 className="font-heading text-xl font-semibold text-foreground">
              HR<span className="text-accent">CompoSure</span>
            </h1>
            <p className="text-xs text-muted-foreground">Terms of Service</p>
          </div>
        </div>
      </header>

      <main className="flex-1 container mx-auto px-4 py-12 max-w-3xl">
        <h2 className="font-heading text-3xl font-semibold text-foreground mb-2">Terms of Service</h2>
        <p className="text-sm text-muted-foreground mb-10">Last updated: May 2026</p>

        <div className="prose prose-sm max-w-none space-y-8 text-foreground">

          <section>
            <h3 className="font-heading text-lg font-semibold mb-2">1. Acceptance of Terms</h3>
            <p className="text-muted-foreground leading-relaxed">
              By creating an account or using HRCompoSure ("the Service"), you agree to these Terms of Service. If you do not agree, do not use the Service. These terms apply to all users, including administrators and team members.
            </p>
          </section>

          <section>
            <h3 className="font-heading text-lg font-semibold mb-2">2. Description of Service</h3>
            <p className="text-muted-foreground leading-relaxed">
              HRCompoSure is a workplace communications platform that helps managers and HR professionals draft sensitive workplace communications, assess communication risk, and maintain employee case records. All content generated is for guidance purposes only and does not constitute legal, medical, or professional HR advice.
            </p>
          </section>

          <section>
            <h3 className="font-heading text-lg font-semibold mb-2">3. Not Professional Advice</h3>
            <p className="text-muted-foreground leading-relaxed">
              <strong>The Service does not provide legal, employment law, medical, or HR consulting advice.</strong> All drafts, risk assessments, and guidance generated by the Service are starting points only. You are solely responsible for reviewing all content before use and for consulting qualified legal and HR professionals for your specific situation. HRCompoSure is not liable for any outcomes resulting from the use of generated content.
            </p>
          </section>

          <section>
            <h3 className="font-heading text-lg font-semibold mb-2">4. Account Responsibilities</h3>
            <ul className="list-disc list-inside space-y-2 text-muted-foreground">
              <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
              <li>You must not share your account with unauthorised individuals.</li>
              <li>You are responsible for all activity that occurs under your account.</li>
              <li>You must notify us immediately of any unauthorised use of your account.</li>
            </ul>
          </section>

          <section>
            <h3 className="font-heading text-lg font-semibold mb-2">5. Acceptable Use</h3>
            <p className="text-muted-foreground leading-relaxed mb-3">You agree not to:</p>
            <ul className="list-disc list-inside space-y-2 text-muted-foreground">
              <li>Use the Service for any unlawful purpose or in violation of applicable employment laws.</li>
              <li>Upload content that infringes intellectual property rights.</li>
              <li>Attempt to reverse engineer, scrape, or access the Service in ways not permitted.</li>
              <li>Use the Service to generate content designed to harass, discriminate against, or harm individuals.</li>
              <li>Share access credentials with individuals outside your organisation.</li>
            </ul>
          </section>

          <section>
            <h3 className="font-heading text-lg font-semibold mb-2">6. Data and Content Ownership</h3>
            <p className="text-muted-foreground leading-relaxed">
              You retain ownership of all content you upload or create within the Service (documents, drafts, case notes). By using the Service, you grant us a limited licence to process your content for the purpose of delivering the Service (e.g. AI generation, retrieval). We do not claim ownership of your content.
            </p>
          </section>

          <section>
            <h3 className="font-heading text-lg font-semibold mb-2">7. Subscription and Billing</h3>
            <ul className="list-disc list-inside space-y-2 text-muted-foreground">
              <li>Paid plans are billed monthly in advance via Stripe.</li>
              <li>You may cancel at any time. Cancellation takes effect at the end of the current billing period.</li>
              <li>We do not offer refunds for partial months, except where required by law.</li>
              <li>We reserve the right to change pricing with 30 days' notice.</li>
            </ul>
          </section>

          <section>
            <h3 className="font-heading text-lg font-semibold mb-2">8. Limitation of Liability</h3>
            <p className="text-muted-foreground leading-relaxed">
              To the maximum extent permitted by law, HRCompoSure shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service, including but not limited to employment disputes, grievances, or legal proceedings arising from the use of generated content. Our total liability to you shall not exceed the amount you paid us in the 3 months prior to the claim.
            </p>
          </section>

          <section>
            <h3 className="font-heading text-lg font-semibold mb-2">9. Service Availability</h3>
            <p className="text-muted-foreground leading-relaxed">
              We aim for high availability but do not guarantee uninterrupted access. We may perform maintenance, updates, or experience outages. We are not liable for any loss resulting from unavailability of the Service.
            </p>
          </section>

          <section>
            <h3 className="font-heading text-lg font-semibold mb-2">10. Termination</h3>
            <p className="text-muted-foreground leading-relaxed">
              We reserve the right to suspend or terminate accounts that violate these Terms. You may close your account at any time. Upon termination, your data will be retained for up to 90 days before deletion, except where legal obligations require otherwise.
            </p>
          </section>

          <section>
            <h3 className="font-heading text-lg font-semibold mb-2">11. Changes to Terms</h3>
            <p className="text-muted-foreground leading-relaxed">
              We may update these Terms from time to time. We will notify you of material changes by email or in-app notice. Continued use of the Service after changes constitutes acceptance.
            </p>
          </section>

          <section>
            <h3 className="font-heading text-lg font-semibold mb-2">12. Governing Law</h3>
            <p className="text-muted-foreground leading-relaxed">
              These Terms are governed by applicable law in the jurisdiction in which HRCompoSure operates. Any disputes shall be resolved through good-faith negotiation in the first instance.
            </p>
          </section>

          <section>
            <h3 className="font-heading text-lg font-semibold mb-2">13. Contact</h3>
            <p className="text-muted-foreground leading-relaxed">
              For questions about these Terms, contact us at <strong className="text-foreground">legal@hrcomposure.com</strong>.
            </p>
          </section>

        </div>
      </main>

      <footer className="border-t border-border py-6 mt-auto">
        <div className="container mx-auto px-4 text-center">
          <p className="text-sm text-muted-foreground">For guidance only. Always consult HR and legal advisors for specific situations.</p>
        </div>
      </footer>
    </div>
  );
}
